### ISSUE TITLE
does work in compiling steams

### ISSUE THREAD

**Issue by tcarlsen** [007design/gulp-prefix#5]
Hey, first off nice package, it was just what I was looking for!

But it looks like it only works on "static" files and not with content coming from other pipes like a jade compiler:

```
return gulp.src('src/index.jade')
    .pipe(jade({pretty: true}))
    .pipe(prefix(prefixUrl, null, '{{'))
```

Gives the error `Error: ENOENT, open '/path/to/project/src/index.html'`

**Comment by alexeybondarenko** [comment]
I've created PR that fix this. https://github.com/007design/gulp-prefix/pull/8
